/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vxi11.h"
#include "scpi_msg_adpt.h"

#define UPO3000_LID 3000

Device_Error *
device_abort_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Create_LinkResp *
create_link_1_svc(Create_LinkParms *argp, struct svc_req *rqstp)
{
	static Create_LinkResp  result;
/*
error           Meaning
0               no error
1               syntax error
3               device not accessible
9               out of resources
11              device locked by another link
21              invalid address

*/
	
	vxi_debug("~argp->clientId=%ld,lockDevice=%d,lock_timeout=%ld,device=%s",
	            argp->clientId,argp->lockDevice,argp->lock_timeout,argp->device); 

	if( strcmp(argp->device, "inst0") == 0 )
	{
		result.error = 0;
		result.lid = UPO3000_LID;
		result.abortPort = 666;
		result.maxRecvSize = 1024;
	}else{ 
		result.error = 3;/* device not accessible*/
		result.lid = 0;
		result.abortPort = 666;//618
		result.maxRecvSize = 1024;
	}

	return &result;
}

Device_WriteResp *
device_write_1_svc(Device_WriteParms *argp, struct svc_req *rqstp)
{
	static Device_WriteResp  result;
	char w_cmd[100];

	vxi_debug("~lid=%ld,len=%d,cmd=%s",argp->lid,argp->data.data_len,argp->data.data_val); 

	result.size = argp->data.data_len;
	result.error = 0x00;
	memset(w_cmd,0,sizeof(w_cmd));
	memcpy(w_cmd,argp->data.data_val,result.size);
	
	if( argp->lid != UPO3000_LID )
	{
		result.error = 0x04;
		return &result;
	}
	scpi_msg_cmd_write(w_cmd,argp->data.data_len);
	//add ....send msg
	vxi_debug("~result.size=%d cmd=%s",result.size,w_cmd); 


	return &result;
}
char device_info[]={"UNI_T,UPO3000,UPO3000CS,0.1"};

Device_ReadResp *
device_read_1_svc(Device_ReadParms *argp, struct svc_req *rqstp)
{
#define VXI11_BUFSIZE (2*1024)
	static Device_ReadResp  result;
	int retValue    =0;
	static char tmp_buf[VXI11_BUFSIZE];
	int host_rcv_cap = 0;/*½ÓÊÕÈÝÁ¿*/
	int response_total_len = scpi_msg_reponse_avail_len();
	int response_sended =0; 
	int response_len = 0;

	/*
	 * insert server code here
	 */
	vxi_debug("~lid=%ld,",argp->lid); 
	
	if( argp->lid == UPO3000_LID )
	{


	retValue = scpi_msg_reponse_read(tmp_buf,response_len);
	result.error = 0;
	result.reason = 0x04;
	result.data.data_len = response_len;
	result.data.data_val = tmp_buf;
	vxi_debug("result.data.data_val = %s \n" , result.data.data_val);

		
	}

	return &result;
}

Device_ReadStbResp *
device_readstb_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_ReadStbResp  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
device_trigger_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
device_clear_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
device_remote_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
device_local_1_svc(Device_GenericParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
device_lock_1_svc(Device_LockParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
device_unlock_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
device_enable_srq_1_svc(Device_EnableSrqParms *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_DocmdResp *
device_docmd_1_svc(Device_DocmdParms *argp, struct svc_req *rqstp)
{
	static Device_DocmdResp  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

Device_Error *
destroy_link_1_svc(Device_Link *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~argp=%d",*argp); 

	return &result;
}

Device_Error *
create_intr_chan_1_svc(Device_RemoteFunc *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

#if 0
	struct svc_req {
	  rpcprog_t rq_prog;			/* service program number */
	  rpcvers_t rq_vers;			/* service protocol version */
	  rpcproc_t rq_proc;			/* the desired procedure */
	  struct opaque_auth rq_cred;	/* raw creds from the wire */
	  caddr_t rq_clntcred;			/* read only cooked cred */
	  SVCXPRT *rq_xprt; 			/* associated transport */
	};

#endif
	/*
	 * insert server code here
	 */
		
	vxi_debug("~argp->hostAddr=%ld,hostPort=%ld,progNum=%ld,progVers=%ld,progFamily=%d",argp->hostAddr,argp->hostPort,
	                                      argp->progNum,argp->progVers,argp->progFamily); 

	return &result;
}

Device_Error *
destroy_intr_chan_1_svc(void *argp, struct svc_req *rqstp)
{
	static Device_Error  result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return &result;
}

void *
device_intr_srq_1_svc(Device_SrqParms *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	vxi_debug("~"); 

	return (void *) &result;
}
